import { TopLevel } from "../interfaces/prices.response";

export const mockPrices: TopLevel[] = [
    {
        id: "price_1PClDAKIMRn2BAKSkuAoXDm9",
        object: "price",
        active: true,
        billing_scheme: "per_unit",
        created: 1714839200,
        currency: "bob",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: {
            id: "prod_Q2quLJ3VuAmcGr",
            object: "product",
            active: true,
            attributes: [],
            created: 1714839199,
            default_price: "price_1PClDAKIMRn2BAKSkuAoXDm9",
            description: "Con esta suscripción podrás utilizar todos los productos por un mes.",
            features: [],
            images: [],
            livemode: false,
            marketing_features: [],
            metadata: {},
            name: "Suscripción por un Mes",
            package_dimensions: null,
            shippable: null,
            statement_descriptor: null,
            tax_code: null,
            type: "service",
            unit_label: null,
            updated: 1714839201,
            url: null
        },
        recurring: {
            aggregate_usage: null,
            interval: "month",
            interval_count: 1,
            meter: null,
            trial_period_days: null,
            usage_type: "licensed"
        },
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "recurring",
        unit_amount: 2000,
        unit_amount_decimal: "2000"
    },
    {
        id: "price_1PClDtKIMRn2BAKSCzCW0Nf1",
        object: "price",
        active: true,
        billing_scheme: "per_unit",
        created: 1714839245,
        currency: "bob",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: {
            id: "prod_Q2qv0557ko8gfo",
            object: "product",
            active: true,
            attributes: [],
            created: 1714839244,
            default_price: "price_1PClDtKIMRn2BAKSCzCW0Nf1",
            description: "Con esta suscripción podras utilizar nuestros productos por 3 meses",
            features: [],
            images: [],
            livemode: false,
            marketing_features: [],
            metadata: {},
            name: "Suscripción por 3 Meses",
            package_dimensions: null,
            shippable: null,
            statement_descriptor: null,
            tax_code: null,
            type: "service",
            unit_label: null,
            updated: 1714839246,
            url: null
        },
        recurring: {
            aggregate_usage: null,
            interval: "month",
            interval_count: 3,
            meter: null,
            trial_period_days: null,
            usage_type: "licensed"
        },
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "recurring",
        unit_amount: 5500,
        unit_amount_decimal: "5500"
    }
]